nodejs:
  image: hmctspublic.azurecr.io/prl/ccd-definitions:latest
  applicationPort: 3000
  autoscaling: # Default is false
    enabled: true
    maxReplicas: 5 # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization

idam-pr:
  enabled: false

xui-webapp:
  enabled: false

tags:
  ccd-pr: false

ccd-case-document-am-api:
  enabled: false

aac-manage-case-assignment:
  enabled: false
