idam-pr:
  enabled: false

xui-webapp:
  enabled: false

xui-mo-webapp:
  enabled: false

tags:
  ccd-pr: false

ccd-case-document-am-api:
  enabled: false

aac-manage-case-assignment:
  enabled: false

prl-cos:
  enabled: true

wa:
  enabled: false

servicebus:
  enabled: false

ccd-message-publisher:
  enabled: false

em-stitching:
  enabled: false

em-ccdorc:
  enabled: false

prl-cron:
  enabled: false

prl-citizen-frontend:
  enabled: false
