# OVERRIDE VALUES IF pr-values:wa tag is applied

xui-webapp:
  enabled: true
  redis:
    enabled: false
    architecture: replication
  nodejs:
    imagePullPolicy: Always
    replicas: 1
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    devcpuRequests: 500m
    devmemoryRequests: 1Gi
    devcpuLimits: 1
    devmemoryLimits: 4Gi
    readinessPeriod: 5
    livenessPeriod: 3
    livenessDelay: 10
    livenessFailureThreshold: 2
    environment:
      HEALTH_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: https://xui-terms-and-conditions-${SERVICE_FQDN}
      HEALTH_ROLE_ASSIGNMENT_API: http://${SERVICE_NAME}-am-role-assignment-service/health
      SERVICES_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: https://ccd-data-store-api-prl-ccd-definitions-pr-${CHANGE_ID}.preview.platform.hmcts.net
      SERVICES_DOCUMENTS_API_V2: http://${SERVICE_NAME}-cdam
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://${SERVICE_NAME}-aac-manage-case-assignment
      SERVICES_TERMS_AND_CONDITIONS: https://xui-terms-and-conditions-${SERVICE_FQDN}
      SERVICES_WORK_ALLOCATION_TASK_API: http://${SERVICE_NAME}-wa-task-management-api
      SERVICES_WA_WORKFLOW_API_URL: http://${SERVICE_NAME}-wa-workflow-api
      SERVICES_ROLE_ASSIGNMENT_API: https://am-role-assignment-service-prl-ccd-definitions-pr-${CHANGE_ID}.preview.platform.hmcts.net
      JURISDICTIONS: PRIVATELAW
      WA_SUPPORTED_JURISDICTIONS: PRIVATELAW
      LAUNCH_DARKLY_CLIENT_ID: 5de6610b23ce5408280f2268
      FEATURE_REDIS_ENABLED: false
      FEATURE_APP_INSIGHTS_ENABLED: false
      FEATURE_SECURE_COOKIE_ENABLED: false
      FEATURE_PROXY_ENABLED: false
      FEATURE_TERMS_AND_CONDITIONS_ENABLED: false
      FEATURE_HELMET_ENABLED: false
      FEATURE_OIDC_ENABLED: false
      FEATURE_JRD_E_LINKS_V2_ENABLED: true
      FEATURE_WORKALLOCATION_ENABLED: ${ENABLE_WA}
      NOW: false
      REDISCLOUD_URL: redis://${SERVICE_NAME}-redis-master:6379
      PROTOCOL: http
      PREVIEW_DEPLOYMENT_ID: "prl-${CHANGE_ID}"
      ENABLE_HEARING_DATA_SOURCE_HEADERS: "true"
      SERVICES_HEARINGS_COMPONENT_API_PRIVATELAW: http://${SERVICE_NAME}-fis-hmc-api
    keyVaults:
      rpx:
        resourceGroup: rpx
        secrets:
          - mc-s2s-client-secret
          - mc-idam-client-secret
          - system-user-name
          - system-user-password

# https://github.com/hmcts/wa-chart/blob/master/wa/values.yaml
wa:
  enabled: ${ENABLE_WA}
  global:
    postgresUsername: hmcts
    postgresSecret: postgres
    postgresHost: private-law-preview.postgres.database.azure.com
    databaseNamePrefix: "pr-${CHANGE_ID}-"
  wa-initiation-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-wa-task-batch"
  wa-reconfiguration-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-reconfiguration"
  wa-termination-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-termination-batch"
  wa-message-cron-service:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-wa-message-cron"

  camunda-bpm:
    java:
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_DB_CONN_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"

  wa-task-management-api:
    java:
      ingressHost: wa-task-management-api-${SERVICE_FQDN}
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
        ALLOWED_JURISDICTIONS: wa,ia,sscs,civil,publiclaw,privatelaw,employment,st_cic
        ALLOWED_CASE_TYPES: asylum,wacasetype,sscs,civil,generalapplication,care_supervision_epo,prlapps,privatelaw_exceptionrecord,et_englandwales,et_scotland,benefit,criminalinjuriescompensation
        MANDATORY_TASK_FIELD_CHECK_ENABLED: true
  wa-case-event-handler:
    java:
      ingressHost: wa-case-event-handler-${SERVICE_FQDN}
      releaseNameOverride: ${SERVICE_NAME}-wa-case-event-handler
      secrets:
        AZURE_SERVICE_BUS_CONNECTION_STRING:
          secretRef: private-law-sb-preview
          key: connectionString
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        CCD_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        CCD_SEARCH_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
        WA_WORKFLOW_API_URL: "http://{{ .Release.Name }}-wa-workflow-api"
        WA_TASK_MANAGEMENT_API_URL: "http://{{ .Release.Name }}-wa-task-management-api"
        AZURE_SERVICE_BUS_TOPIC_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-ccd-case-events

  wa-task-monitor:
    java:
      ingressHost: wa-task-monitor-${SERVICE_FQDN}
      environment:
        WA_TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api

  wa-workflow-api:
    java:
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        DB_READER_USERNAME: "hmcts"

  wa:
    postgresql:
      enabled: false

servicebusPrimary:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}
  resourceGroup: private-law-aso-preview-rg
  sbNamespace: private-law-servicebus-preview
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true

ccd-message-publisher:
  enabled: true
  servicebusPrimary:
    enabled: false
  java:
    ingressHost: ccd-message-publisher-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-ccd-message-publisher
    disableKeyVaults: true # TODO - check if this can be disabled or not
    devcpuRequests: 500m
    devmemoryRequests: 1Gi
    devcpuLimits: 1
    devmemoryLimits: 4Gi
    environment:
      DATA_STORE_DB_HOST: private-law-preview.postgres.database.azure.com
      DATA_STORE_DB_NAME: "pr-${CHANGE_ID}-data-store"
      DATA_STORE_DB_USERNAME: hmcts
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CCD_CASE_EVENTS_DESTINATION: ${SERVICE_NAME}-ccd-case-events
    secrets:
      SERVICE_BUS_CONNECTION_STRING:
        secretRef: private-law-sb-preview
        key: connectionString
      DATA_STORE_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: false
